# CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_no_attack --options-file '/efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise 2023.08.05--06-57-33/options-and-config.pickle' --checkpoint-file '/efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise 2023.08.05--06-57-33/checkpoints/combined-noise--epoch-500.pyt' --end 1000 --with_tracking
# python test_model_watermark.py --run_name run_HiDDeN_wm_cr_cs --options-file experiments/combined-noise/options-and-config.pickle --checkpoint-file experiments/combined-noise/checkpoints/combined-noise--epoch-400.pyt --end 1000 --with_tracking --crop_scale 0.75 --crop_ratio 0.75
# python test_model_watermark.py --run_name run_HiDDeN_wm_rotation --options-file experiments/combined-noise/options-and-config.pickle --checkpoint-file experiments/combined-noise/checkpoints/combined-noise--epoch-400.pyt --end 1000 --with_tracking --r_degree 75
# python test_model_watermark.py --run_name run_HiDDeN_wm_jpeg --options-file experiments/combined-noise/options-and-config.pickle --checkpoint-file experiments/combined-noise/checkpoints/combined-noise--epoch-400.pyt --end 1000 --with_tracking --jpeg_ratio 25
# python test_model_watermark.py --run_name run_HiDDeN_wm_gaussian_blur --options-file experiments/combined-noise/options-and-config.pickle --checkpoint-file experiments/combined-noise/checkpoints/combined-noise--epoch-400.pyt --end 1000 --with_tracking --gaussian_blur_r 4
# python test_model_watermark.py --run_name run_HiDDeN_wm_gaussian_std --options-file experiments/combined-noise/options-and-config.pickle --checkpoint-file experiments/combined-noise/checkpoints/combined-noise--epoch-400.pyt --end 1000 --with_tracking --gaussian_std 0.1
# python test_model_watermark.py --run_name run_HiDDeN_wm_brightness --options-file experiments/combined-noise/options-and-config.pickle --checkpoint-file experiments/combined-noise/checkpoints/combined-noise--epoch-400.pyt --end 1000 --with_tracking --brightness_factor 6


for epoch in 300 400 500
do
    echo running epoch ${epoch}
    CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_512_ep${epoch}_no_attack --options-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/options-and-config.pickle --checkpoint-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/checkpoints/combined-noise--epoch-${epoch}.pyt --end 1000 --with_tracking
    CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_512_ep${epoch}_cr_cs --options-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/options-and-config.pickle --checkpoint-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/checkpoints/combined-noise--epoch-${epoch}.pyt --end 1000 --with_tracking --crop_scale 0.75 --crop_ratio 0.75
    CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_512_ep${epoch}_rotation --options-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/options-and-config.pickle --checkpoint-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/checkpoints/combined-noise--epoch-${epoch}.pyt --end 1000 --with_tracking --r_degree 75
    CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_512_ep${epoch}_jpeg --options-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/options-and-config.pickle --checkpoint-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/checkpoints/combined-noise--epoch-${epoch}.pyt --end 1000 --with_tracking --jpeg_ratio 25
    CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_512_ep${epoch}_gaussian_blur --options-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/options-and-config.pickle --checkpoint-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/checkpoints/combined-noise--epoch-${epoch}.pyt --end 1000 --with_tracking --gaussian_blur_r 4
    CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_512_ep${epoch}_gaussian_std --options-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/options-and-config.pickle --checkpoint-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/checkpoints/combined-noise--epoch-${epoch}.pyt --end 1000 --with_tracking --gaussian_std 0.1
    CUDA_VISIBLE_DEVICES=0 python test_model_watermark.py --run_name run_HiDDeN_wm_512_ep${epoch}_brightness --options-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/options-and-config.pickle --checkpoint-file /efs/users/yongxinw/experiments/HiDDeN_512-DP-lr1e-3-bs48-500ep-coco17-crop_cropOut_drop_jpeg/runs/combined-noise--2023.08.05--06-57-33/checkpoints/combined-noise--epoch-${epoch}.pyt --end 1000 --with_tracking --brightness_factor 6
done


python main.py new \
--name 'combined-noise' \
--data-dir /efs/users/yongxinw/data/mscoco/for_hidden/ \
--batch-size 32 \
--noise  "crop((0.4,0.55),(0.4,0.55))+cropout((0.25,0.35),(0.25,0.35))+dropout(0.25,0.35)+resize(0.4,0.6)+jpeg()" \
--epochs 500 --size 512 \
--runs_folder /efs/users/yongxinw/experiments/HiDDeN_512-DP-Test